var CONSTANTS = {
    TOTAL_BOTTOM_MINUTES_LAMP: "4",
    TIME_PER_LAMP_MINUTES: "5",
    YELLOW: "Y",
    OFF: "O",
    RED: "R",
    TOTAL_TOP_MINUTES_LAMP: "11",
    TOTAL_HOURS_LAMP: "4",
    TIME_PER_LAMP_HOURS: "5"

};
module.exports = CONSTANTS;